# Generated by Django 4.1.1 on 2022-11-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cart_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
